Merge the RadMon data extract source code into rrfs_util.
NOAA-GSL/rrfs_utl pull request #46
Opened 2023-10-03 03:44 UTC by xyzemc

https://github.com/NOAA-GSL/rrfs_utl/issues/43
The data extract step from RadMon include four packs of source code:
verf_radang.fd/  
verf_radbcoef.fd/  
verf_radbcor.fd/ 
verf_radtime.fd/

All these codes have put in the directory 'radmon' under rrfs_util. The corresponding makefile has been modified and tested.  Four executables will be placed into the ./bin directory as other codes.

2023-10-03 04:39 UTC, hu5970 approved these changes

2023-10-03 14:11 UTC, christopherwharrop-noaa requested changes
There is a lot of duplication in this pull request.  The specification of compiler flags for different compilers should ideally be done in one place for the entire repository, not duplicated verbatim in multiple places.  Additionally, the introduction of multiple `kinds.f90` creates unnecessary duplication, particularly since rrfs_utls already has a kinds module.  Please remove duplication and make use of existing code and build specifications where possible.

2023-10-03 14:37 UTC, hu5970 commented
@christopherwharrop-noaa This repository is to host many small applications for RRFS. Some of those applications are isolated from others. I agree it is good to reduce the duplication. We also need to check this case by case. "kind.f90" used here may not have the same definition as the kinds module used by other. Do we have a way to keep some code used locally (like kinds.f90 only used by this application)? The same possible is also applying for compiling options.

2023-10-03 18:38 UTC, xyzemc commented
@christopherwharrop-noaa @hu5970 I will compare the kind.f90 in this PR and the existing kind.f90 in rrfs_util to see if they are same and can avoid the duplication.

2023-11-02 02:46 UTC, hu5970 commented
@xyzemc Please remove save directory and sync with current develop branch.

2023-11-02 15:58 UTC, christopherwharrop-noaa requested changes
Thank you for taking the time to address my comments.  This looks great!  There are a couple commented lines in `CMakeLists.txt` files that should be removed, and you might also consider removing what look like (I'm not sure) commented out debugging `write` statements.  Once the Cmake comments are removed, I'll approve.

2023-11-02 15:58 UTC, christopherwharrop-noaa commented on radmon/shared/CMakeLists.txt
> +#target_link_libraries(radmonlib PUBLIC ${PROJECT_NAME}::ncio)
Please remove commented code

2023-11-02 15:58 UTC, christopherwharrop-noaa commented on radmon/verf_radbcoef.fd/CMakeLists.txt
> +#include_directories( /scratch1/BMC/wrfruc/mhu/rrfs/v0.7.1/ufs-srweather-app/include )
Please remove commented code

2023-11-02 15:58 UTC, christopherwharrop-noaa commented on radmon/verf_radtime.fd/bad_chan.f90
> +!      write(*,*) '--> open_bad_chan_file, date, cycle = ', date, cycle
This looks like commented code leftover from debugging.  Perhaps it should be removed?

2023-11-02 15:58 UTC, christopherwharrop-noaa commented on radmon/verf_radtime.fd/bad_penalty.f90
> +!      write(*,*) '--> open_bad_penalty_file, date, cycle = ', date, cycle
This looks like commented code leftover from debugging.  Perhaps it should be removed?

2023-11-02 20:17 UTC, christopherwharrop-noaa approved these changes
Thank you for making those last few updates.

2023-11-02 22:45 UTC, merged